[package]
name = "tower-sessions-core"
description = "Core types and traits for tower-sessions."
documentation.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = []
axum-core = ["dep:axum-core"]
deletion-task = ["tokio/time"]

[dependencies]
async-trait = { workspace = true }
axum-core = { version = "0.4", optional = true }
base64 = "0.22.0"
futures = { version = "0.3.28", default-features = false, features = [
    "async-await",
] }
http = "1.0"
parking_lot = { version = "0.12.1", features = ["serde"] }
rand = "0.8.5"
serde = { version = "1.0.189", features = ["derive", "rc"] }
serde_json = "1.0.107"
thiserror = { workspace = true }
time = { version = "0.3.29", features = ["serde"] }
tokio = { workspace = true }
tracing = { version = "0.1.40", features = ["log"] }

[dev-dependencies]
tower-sessions = { workspace = true, features = ["memory-store"] }
tokio-test = "0.4.3"
tokio = { workspace = true, features = ["rt", "macros"] }
mockall = "0.13.0"
