[package]
name = "tower-sessions-core"
description = "Core types and traits for tower-sessions."
documentation.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = ["axum-core"]
axum-core = ["dep:axum-core"]
deletion-task = ["tokio/time"]

[dependencies]
async-trait = "0.1.73"
axum-core = { version = "0.4.0", optional = true }
base64 = "0.21.7"
futures = { version = "0.3.28", default-features = false, features = [
    "async-await",
] }
http = "1.0"
parking_lot = { version = "0.12.1", features = ["serde"] }
rand = "0.8.5"
serde = { version = "1.0.189", features = ["derive", "rc"] }
serde_json = "1.0.107"
thiserror = "1.0.49"
time = { version = "0.3.29", features = ["serde"] }
tokio = { version = "1.32.0", features = ["sync"] }
tower-cookies = "0.10.0"
tower-layer = "0.3.2"
tower-service = "0.3.2"
tracing = { version = "0.1.40", features = ["log"] }

[dev-dependencies]
tower-sessions = { workspace = true }
tower-sessions-sqlx-store = { version = "0.9.2", features = [
    "postgres",
    "sqlite",
    "mysql",
] }
tower-sessions-moka-store = { version = "0.9.1" }
tokio-test = "0.4.3"
